name: spyproject2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - lxml
  - flask
  - matplotlib
  - tqdm
  - pip:
      - altgraph
      - appdirs
      - beautifulsoup4
      - blinker
      - cachelib
      - certifi
      - charset-normalizer
      - click
      - colorama
      - dash
      - dash-bootstrap-components
      - dash-core-components
      - dash-html-components
      - dash-table
      - filelock
      - frozendict
      - html5lib
      - idna
      - importlib-metadata
      - itsdangerous
      - jinja2
      - joblib
      - lz4
      - markupsafe
      - msgpack
      - multitasking
      - packaging
      - peewee
      - pefile
      - plotly
      - psutil
      - pyinstaller
      - pyinstaller-hooks-contrib
      - python-dateutil
      - pytz
      - requests
      - retrying
      - six
      - soupsieve
      - tenacity
      - typing-extensions
      - tzdata
      - urllib3
      - webencodings
      - werkzeug
      - yfinance
      - zipp
